POST {{host}}/archive
Authorization: Basic local-dev local-dev
Content-Type: application/json

{
  "package_names": [
    "curl",
    "vim"
  ]
}

###

POST {{host}}/archive
Authorization: Basic local-dev local-dev
Content-Type: application/json

{
  "package_names": [
    "qwertzuiasdfghj"
  ]
}