POST {{host}}/archive
Authorization: Basic {{username}} {{passworrd}}
Content-Type: application/json

{
  "package_names": [
    "curl",
    "vim"
  ]
}

###

POST {{host}}/archive
Authorization: Basic {{username}} {{passworrd}}
Content-Type: application/json

{
  "package_names": [
    "qwertzuiasdfghj"
  ]
}