name: Create and publish a Docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version tag
        required: true

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.event.inputs.image }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Setup timezone to Europe/Zurich
        run: |
          sudo timedatectl set-timezone Europe/Zurich
          timedatectl

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{ defaultContext }}:docker"
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/386,linux/ppc64le,linux/s390x
          pull: true
          push: true
          tags: viascom/alpine-packages:${{ github.event.inputs.version }}